### ISSUE TITLE
[GSSOC] Enhancing the UI of the LogIn/SignUp Form

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [narayan954/dummygram#1003]
### Description

The landing page or the page from where a new user gets the first impression of the website must have an engaging design and should provide a good user experince.

The current landing or the loginForm can be enhanced by adding more styling and adding more CSS which would in turn help increase user experience.
In the current login page the image does not go with the overall theme disrupting the look of UI also the show password button has been misplaced.
The login inputs look a bit dull which can be styled to modern aspects.

I would love to work on it by adding more CSS styling to the landing page form. I would use more engaging input fields and a better overall theme to increase engagement from users. This would help improve the UI of the app.
Please do assign me.
Thanks

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/97378312/1b7e1854-acd1-441c-ab1d-7dfe8da623dd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Sure, you can go ahead! @rishabhchaudhary0210

**Comment by rishabhchaudhary0210** [comment]
Hey @narayan954 Thanks for assigning, I will soon complete the task and issue the PR.

**Comment by suveshmoza** [comment]
The content of the div containing the form and dummygram logo has excess margin on the top pushing down the sign up and forgot password. When using dark mode, the text below the logo is not visible and sign-up form also needs some styling. If the issue is still open, I would like to work on this. @narayan954 


|![Screenshot from 2023-08-21 00-16-30](https://github.com/narayan954/dummygram/assets/56023604/afd4437f-2164-4653-afde-600db7049666)|![Screenshot from 2023-08-21 00-16-15](https://github.com/narayan954/dummygram/assets/56023604/3956e039-3904-43f0-9144-ef37f679e839)|![Screenshot from 2023-08-21 00-25-41](https://github.com/narayan954/dummygram/assets/56023604/b93ec719-9cf8-40b6-ae3a-32b67c7082bf)|
|-|-|-|

**Comment by narayan954** [comment]
> The content of the div containing the form and dummygram logo has excess margin on the top pushing down the sign up and forgot password. When using dark mode, the text below the logo is not visible and sign-up form also needs some styling. If the issue is still open, I would like to work on this. @narayan954
> 
> ![Screenshot from 2023-08-21 00-16-30](https://user-images.githubusercontent.com/56023604/261870932-afd4437f-2164-4653-afde-600db7049666.png)	![Screenshot from 2023-08-21 00-16-15](https://user-images.githubusercontent.com/56023604/261870937-3956e039-3904-43f0-9144-ef37f679e839.png)	![Screenshot from 2023-08-21 00-25-41](https://user-images.githubusercontent.com/56023604/261871398-b93ec719-9cf8-40b6-ae3a-32b67c7082bf.png)

Hi @suveshmoza  thanks a lot for raising the issue. Yeah sure you can work on them! :)
