### ISSUE TITLE
[FEATURE] Post Delete feature

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#77]
### Description

We can delete any post by id through firebase cloud firestore delete request
for example = { const res = await db.collection('posts').doc('0DJEyHXRk6b4yyym3NYC').delete(); }

Can we try to implement this in our web application?
Ps: Only post creator should be able to delete his post.

**Comment by tanishk-23** [comment]
@narayan954  Can you please assign this issue to me?

**Comment by narayan954** [comment]
sure, go ahead @tanishk-23

**Comment by tanishk-23** [comment]
I have implemented the post delete feature but i want some information regarding database schemas so that i can check whether a user can delete the post or not?

![DeletePost1](https://user-images.githubusercontent.com/72482878/194891952-e4a8788e-c2d7-426a-b93b-1fd9b5d657f5.JPG)
![DeletePost2](https://user-images.githubusercontent.com/72482878/194892005-d6658bd2-93ef-427f-80e2-f70528898171.JPG)

**Comment by narayan954** [comment]
okay sure @tanishk-23 , I think I should give you a glimpse of the current firestore db

**Comment by narayan954** [comment]
![image](https://user-images.githubusercontent.com/77617189/194915656-fa187c32-a969-44d2-9365-4e8472cc36e7.png)
would this do?

**Comment by tanishk-23** [comment]
@narayan954 I think there should be user id associated with the post so that we can check whether user can delete it or not

**Comment by narayan954** [comment]
posts do have an id attribute, as they are mapped with ids (line 116 of app.jsx). You can access/delete any post directly by id from firebase firestore. I hope this helps.
